# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='carte_didentite_nationale',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
