# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20180424_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='idcarte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employers',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
