# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20180502_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
