# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_auto_20180503_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='photo2',
            field=models.FileField(null=True, upload_to='employers/'),
        ),
    ]
