# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_employers_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='photo2',
        ),
    ]
