# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_auto_20180614_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='carte_didentite_nationale',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employers',
            name='email',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='employers',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
