# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_autorisation',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur2',
            name='status_email',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]
