# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171116_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur2',
            name='status_email',
        ),
    ]
