# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paiement_statisque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('idPaiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.CharField(blank=True, max_length=22, null=True)),
                ('date_fin', models.CharField(blank=True, max_length=22, null=True)),
                ('nbseances_en_cours', models.IntegerField(default=0)),
                ('nbseances_total', models.IntegerField(default=0)),
                ('dateencours', models.CharField(blank=True, max_length=22, null=True)),
                ('date_autorisation', models.CharField(blank=True, max_length=22, null=True)),
                ('datebadge', models.CharField(blank=True, max_length=32, null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur2')),
            ],
        ),
    ]
