# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur2',
            name='status_email',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
