# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur2_status_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_parrainage', models.DateTimeField(auto_now_add=True)),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filleul', to='users.utilisateur2')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrain', to='users.utilisateur2')),
            ],
        ),
    ]
