# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
