# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsss', '0002_adminss_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminss',
            name='activation_token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
