# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsss', '0003_adminss_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminss',
            name='telephone',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
