# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essaies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne_essaie',
            name='civilte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
