# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essaies', '0002_personne_essaie_civilte'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne_essaie',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
