# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essaies', '0003_personne_essaie_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne_essaie',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
